version: "3"

services:
  mongodb:
    container_name: database
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - ./app/db/data:/data/db
    networks:
      - frontend
      - backend

  redis:
    image: "redis:alpine"
    container_name: container-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./app/redis_data:/data

  web_app:
    container_name: web_app
    build: .
    image: kaneai/mango-test-api
    restart: always
    depends_on:
      - mongodb
      - redis
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
    networks:
      - backend
#    env_file:
#      - .env

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge




