version: "3"

services:
  mongodb:
    container_name: database
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - ./app/db/data:/data/db
    networks:
      - microservice
      - default

  web_app:
    container_name: web_app
    build: .
    image: kaneai/mango-test-api
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
    env_file:
      - .env

networks:
  default:
    external:
      name: student_network
  microservice:
    external:
      name: microservice_network
